sudo: false
addons:
    chrome: stable
    postgresql: "10"
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10
env:
    global:
        - PGPORT=5433
        - KINGFISHER_PROCESS_DB_URI='postgres:///travis'
services:
    - postgresql
language: python
python:
    - "3.5"

install:
    - "pip install -r requirements_dev.txt"
script:
    - "flake8 ocdskingfisherprocess/ ocdskingfisher-process-cli tests setup.py"
    - "KINGFISHER_PROCESS_WEB_API_KEYS=1234 py.test"
